version: '3.8'

services:
  currency_converter:
    build:
      context: .
      dockerfile: Dockerfile
    image: currency_converter_app
    container_name: currency_converter
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
    network_mode: host
    tty: true